swagger: "2.0"
info:
  version: "1.0.0"
  title: API
  description: blah
host: localhost:3000
basePath: /
paths:
  /properties:
    post:
      summary: Creates a new Property
      consumes:
        - application/json
      parameters:
        - in: body
          name: property
          description: trying hard to make this work
          schema:
            $ref: "../swagger/components.yaml#/components/schemas/Property"
            example:
              id: 1
              address: 123 Test Ave
              city: San Antonio
              state: TX
              zip: 78222
      responses:
        "200":
          description: Successfule Created a Property
