swagger: "2.0"
info:
  version: "1.0.0"
  title: API
  description: blah
host: localhost:3000
basePath: /
tags:
  - name: Hello
    description: Hello
  - name: Property
    description: Property

paths:
  /hello:
    get:
      description: OK
      tags:
        - Hello
      responses:
        "200":
          description: OK
  /properties:
    post:
      summary: Creates a new Property
      tags:
        - Property
      consumes:
        - application/json
      parameters:
        - in: body
          name: property
          description: trying hard to make this work
          schema:
            $ref: "../swagger/definitions.yaml#/definitions/Property"
      responses:
        "200":
          description: Successfully Created a Property

  /properties/{propertyId}:
    get:
      summary: Get a Property by propertyId
      tags:
        - Property
      parameters:
        - in: path
          name: propertyId
          type: integer
          required: true
          description: Numberic ID of the property to get
      responses:
        "200":
          description: Successfully Retrived a Property
          schema:
            $ref: "../swagger/definitions.yaml#/definitions/Property"
